# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

repository: "ocmod-space/ocmod-space.github.io"
remote_theme: underr-ua/minimal-mistakes-jekyll-theme
# minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
theme_default: default
theme_alternative: dark

timezone: Europe/Kyiv # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

breadcrumbs: false
markdown: kramdown

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

permalink: /:slug/

search: true

title: "ocmod.space"
subtitle: "opencart modules development"
title_separator: "|"
description: >- # this means to ignore newlines until "baseurl:"
  OpenCart Modules and Extensions.

name: &name "Andrii B." # &name is a YAML anchor which can be *referenced later
logo: "/assets/images/logo.png"
masthead_title: # overrides the website title displayed in the masthead, use " " for no title
teaser: # path of fallback teaser image, e.g.

# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/photo.jpg"
  bio              : "Just another OpenCart module developer..."
  location         : "Ukraine"
  links:
    - label: "OpenCart"
      icon: "fab fa-fw fa-opencart"
      url: "https://www.opencart.com/index.php?route=marketplace/extension&filter_member=ocmod.space"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ocmod-space"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/underr"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ocmod_space"

footer:
  links:
    - label: "OpenCart"
      icon: "fab fa-fw fa-opencart"
      url: "https://www.opencart.com/index.php?route=marketplace/extension&filter_member=ocmod.space"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ocmod-space"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/underr"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ocmod_space"

# Google services
analytics:
  provider: "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id: "G-6Q9XW0BCSJ"
    anonymize_ip: true # true, false (default)
reCaptcha:
  siteKey: "6LcrhwElAAAAAKIQ5OmXPsHKawtuRBah7YRVKrUC"
  secret: "6LcrhwElAAAAAH7KngSa0QWXNC4DE38fOOIULS0B"
google_site_verification: "KJLffCCe_c_Kh_Ru_bQX6A9tpfBTbCOI5UNDsiE2lo4"

# comments
comments:
  provider: "giscus"
  giscus:
    repo_id: "R_kgDOJHyDMw"
    category_name: "Announcements"
    category_id: "DIC_kwDOJHyDM84CVE8z" # Shown during giscus setup at https://giscus.app
    discussion_term: "title" # "pathname" (default), "url", "title", "og:title"
    reactions_enabled: "1"
    theme: "preferred_color_scheme" # "light" (default), "dark", "dark_dimmed", "transparent_dark"
    # added attributes
    strict: "1"
    position: top # "top", "bottom"
    metadata: "0"
    lang: "en"
    lazy: true
